### ISSUE TITLE
Question about your project TheNewC0der-24 / CLOUD-COACH-New-UI

### ISSUE THREAD

**Issue by Jaygucc95** [TheNewC0der-24/TheNewC0der-24#3]
Hi there! I am an experienced SaaS sales professional  and have experience running a start up,with a solid track record of success. I am currently working on an innovative solution that has already generated interest from potential clients. I have the business side of things covered, but need a strong product to bring to market. I would love to connect and discuss how we can work together to bring this idea to life. Thank you for considering.

**Comment by TheNewC0der-24** [comment]
Hi, Hope you are doing well. I would love to work with you.

**Comment by Jaygucc95** [comment]
I emailed you back lets connect now?

**Comment by TheNewC0der-24** [comment]
Sure

**Comment by Jaygucc95** [comment]
https://meet.google.com/hzv-djov-ona?authuser=2 here is the link

**Comment by TheNewC0der-24** [comment]
End
